blueprint:
  name: Family Bell (Minimal, tts.google_en_com)
  domain: automation
  input:
    media_players:
      name: Speakers
      selector:
        target:
          entity:
            domain: media_player
    bell_time:
      name: Time
      selector:
        time: {}
    weekdays:
      name: Days of week
      selector:
        select:
          mode: list
          multiple: true
          options: [mon, tue, wed, thu, fri, sat, sun]
      default: [mon, tue, wed, thu, fri]
    message:
      name: Message
      selector:
        text:
          multiline: true

mode: single

trigger:
  - platform: time
    at: !input bell_time

condition:
  - condition: time
    weekday: !input weekdays

action:
  - service: tts.google_en_com
    target: !input media_players
    data:
      message: !input message