blueprint:
  name: Family Bell (TTS entity + tts.speak, per-speaker)
  domain: automation
  description: >
    Speak a message on selected weekdays at a set time using a TTS entity
    (e.g., tts.google_en_com). Loops each selected media_player.

  input:
    tts_entity:
      name: TTS voice/entity
      selector:
        entity:
          domain: tts
    media_players:
      name: Speakers (pick one or more)
      selector:
        entity:
          domain: media_player
          multiple: true
    bell_time:
      name: Time
      selector:
        time: {}
    weekdays:
      name: Days of week
      selector:
        select:
          mode: list
          multiple: true
          options: [mon, tue, wed, thu, fri, sat, sun]
      default: [mon, tue, wed, thu, fri]
    message:
      name: Message to speak
      selector:
        text:
          multiline: true

mode: single

trigger:
  - platform: time
    at: !input bell_time

condition:
  - condition: time
    weekday: !input weekdays

action:
  - repeat:
      for_each: !input media_players
      sequence:
        - service: tts.speak
          target:
            entity_id: !input tts_entity
          data:
            media_player_entity_id: "{{ repeat.item }}"
            message: !input message